import { z } from "zod";

export const _stateSchema = z.enum(["published", "new", "migration"]);
export const _cohortSchema = z.enum(["2020-2023", "2023-2024", "0"]);

export const phaseSlugs = z.enum(["foundation", "primary", "secondary"]);
export const phaseDescriptions = z.enum([
  "Early Years Foundation Stage",
  "Primary",
  "Secondary",
]);
export const phases = z.enum(["foundation", "primary", "secondary"]);

export const keystages = z.enum(["KS1", "KS2", "KS3", "KS4", "EYFS"]);
export const keystageSlugs = z.enum([
  "ks1",
  "ks2",
  "ks3",
  "ks4",
  "early-years-foundation-stage",
]);
export const keystageDescriptions = z.enum([
  "Key Stage 1",
  "Key Stage 2",
  "Key Stage 3",
  "Key Stage 4",
  "Early Years Foundation Stage",
]);

export const years = z.enum([
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "R",
]);
export const yearSlugs = z.enum([
  "reception",
  "year-1",
  "year-2",
  "year-3",
  "year-4",
  "year-5",
  "year-6",
  "year-7",
  "year-8",
  "year-9",
  "year-10",
  "year-11",
  "year-12",
  "year-13",
]);
export const yearDescriptions = z.enum([
  "Year 1",
  "Year 2",
  "Year 3",
  "Year 4",
  "Year 5",
  "Year 6",
  "Year 7",
  "Year 8",
  "Year 9",
  "Year 10",
  "Year 11",
  "Year 12",
  "Year 13",
  "Reception",
]);

export const tiers = z.enum(["core", "foundation", "higher"]);
export const tierSlugs = z.enum(["core", "foundation", "higher"]);
export const tierDescriptions = z.enum(["Core", "Foundation", "Higher"]);

export const examboardSlugs = z.enum([
  "aqa",
  "edexcel",
  "eduqas",
  "ocr",
  "wjec",
]);
export const examboards = z.enum(["AQA", "Edexcel", "Eduqas", "OCR", "WJEC"]);
export const examboardDescriptions = z.enum([
  "Assessment and Qualifications Alliance",
  "Edexcel",
  "Eduqas",
  "Oxford, Cambridge and RSA Examinations",
  "Welsh Joint Education Committee",
]);

export const subjects = z.enum([
  "English",
  "Geography",
  "History",
  "Maths",
  "Music",
  "Science",
  "Biology",
  "Physics",
  "Chemistry",
  "Combined science",
  "Art and design",
  "Citizenship",
  "Computing",
  "Computing (non-GCSE)",
  "Design and technology",
  "Drama",
  "English grammar",
  "English reading for pleasure",
  "English spelling",
  "Expressive arts and design",
  "French",
  "German",
  "Latin",
  "Literacy",
  "Physical education",
  "Personal, social and emotional development",
  "Religious education",
  "RSHE (PSHE)",
  "Spanish",
  "Understanding the world",
  "Therapies",
  "Occupational therapy",
  "Physical therapy",
  "Sensory integration",
  "Speech and language therapy",
  "Specialist",
  "Physical development",
  "Communication and language",
  "Creative arts",
  "Independent living",
  "Numeracy",
  "GCSE citizenship",
  "Core citizenship",
  "Computer science",
  "Core computing",
  "GCSE physical education",
  "Core physical education",
  "GCSE religious education",
  "Core religious education",
  "QA testing only",
  "Relationships, sex and health education",
]);
export const subjectSlugs = z.enum([
  "english",
  "geography",
  "history",
  "maths",
  "music",
  "science",
  "biology",
  "physics",
  "chemistry",
  "combined-science",
  "art",
  "citizenship",
  "computing",
  "computing-non-gcse",
  "design-technology",
  "drama",
  "english-grammar",
  "english-reading-for-pleasure",
  "english-spelling",
  "expressive-arts-and-design",
  "french",
  "german",
  "latin",
  "literacy",
  "physical-education",
  "personal-social-and-emotional-development",
  "religious-education",
  "rshe-pshe",
  "spanish",
  "understanding-the-world",
  "therapies",
  "occupational-therapy",
  "physical-therapy",
  "sensory-integration",
  "speech-and-language-therapy",
  "specialist",
  "physical-development",
  "communication-and-language",
  "creative-arts",
  "independent-living",
  "numeracy",
  "gcse-citizenship",
  "core-citizenship",
  "computer-science",
  "core-computing",
  "gcse-physical-education",
  "core-physical-education",
  "gcse-religious-education",
  "core-religious-education",
  "rshe",
]);
